# -*- coding: utf-8 -*-
"""11.29_RS2SVI_Sat2Street_ControlNet_SD_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UvRDGhoguiaW-i-Y0zVmApc02BVlsmx3
"""

from google.colab import drive
drive.mount('/content/drive')

# 这里改成你在 Drive 里的真实路径（重点！）
# 比如：/content/drive/MyDrive/Dataset/CVIAN_reorganized
RAW_DATA_ROOT = "/content/drive/MyDrive/Manuscript_Ph.D./3rd_DisasterMind AI agent (organization）/Dataset/CVIAN_reorganized"


WORK_DIR = "/content/sat2street_data"
IMG_DIR  = f"{WORK_DIR}/images"
PAIRS_CSV = f"{WORK_DIR}/pairs.csv"

import os
os.makedirs(IMG_DIR, exist_ok=True)

!ls "/content/drive/MyDrive/Manuscript_Ph.D./3rd_DisasterMind AI agent (organization）/Dataset"

import os
import shutil
import csv

severities = ["0_MinorDamage", "1_ModerateDamage", "2_SevereDamage"]

rows = []
idx = 0

for sev in severities:
    sev_dir = os.path.join(RAW_DATA_ROOT, sev)
    if not os.path.isdir(sev_dir):
        continue

    for folder in sorted(os.listdir(sev_dir)):
        folder_path = os.path.join(sev_dir, folder)
        if not os.path.isdir(folder_path):
            continue

        files = os.listdir(folder_path)
        sat_files = [f for f in files if "Satellite" in f]
        svi_files = [f for f in files if "SVI" in f]

        if not sat_files or not svi_files:
            continue

        sat_src = os.path.join(folder_path, sat_files[0])
        svi_src = os.path.join(folder_path, svi_files[0])

        sat_dst = os.path.join(IMG_DIR, f"{idx:06d}_sat.png")
        svi_dst = os.path.join(IMG_DIR, f"{idx:06d}_svi.png")

        shutil.copy(sat_src, sat_dst)
        shutil.copy(svi_src, svi_dst)

        rows.append([sat_dst, svi_dst, sev])  # 把 severity 也保存一下
        idx += 1

print("Total pairs:", len(rows))

with open(PAIRS_CSV, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["sat_path", "svi_path", "severity"])
    writer.writerows(rows)

print("Pairs CSV saved at:", PAIRS_CSV)

import shutil
import os
from google.colab import drive

# 1. 挂载 Google Drive
print("正在挂载 Google Drive...")
drive.mount('/content/drive')

# 2. 定义源文件夹和压缩包名称
source_folder = '/content/sat2street_data'  # 你的数据根目录
output_filename = '/content/sat2street_dataset_backup' # 压缩包的临时名字 (不带.zip后缀，程序会自动加)
destination_path = '/content/drive/MyDrive/sat2street_dataset_backup.zip' # 最终存到网盘的位置

# 3. 开始压缩
print(f"正在压缩文件夹: {source_folder}，文件较多请稍候...")
shutil.make_archive(output_filename, 'zip', source_folder)
print("压缩完成！")

# 4. 移动到 Google Drive
print(f"正在复制到 Google Drive: {destination_path} ...")
shutil.copy(f"{output_filename}.zip", destination_path)

print(f"✅ 成功！文件已保存在你的 Google Drive 根目录下，文件名为: sat2street_dataset_backup.zip")

!pip install -q diffusers transformers accelerate xformers torch torchvision pandas pillow opencv-python

import zipfile
import os

# 你的备份文件在 Drive 里的路径
zip_path = '/content/drive/MyDrive/sat2street_dataset_backup.zip'
extract_path = '/content/sat2street_data' # 解压目标位置

if not os.path.exists(extract_path):
    print(f"正在解压数据到 {extract_path} ...")
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print("✅ 解压完成！")
else:
    print("✅ 文件夹已存在，无需重复解压。")

# 1. 运行你截图里的那个 Class 定义代码

# 2. 运行下面这段测试代码
csv_file_path = '/content/sat2street_data/pairs.csv' # 确保这个路径对

try:
    dataset = Sat2StreetDataset(csv_file_path, resolution=512)
    sample = dataset[0] # 尝试读取第一张图

    print(f"✅ 数据集测试通过！共找到 {len(dataset)} 组数据。")
    print(f"Street View Shape: {sample['pixel_values'].shape} (预期: 3, 512, 512)")
    print(f"Satellite Shape: {sample['condition_pixel_values'].shape} (预期: 3, 512, 512)")
    print(f"Prompt: {sample['input_ids']}")

except Exception as e:
    print("❌ 出错了！可能是路径不对。错误信息：")
    print(e)

import torch
import torch.nn.functional as F
from accelerate import Accelerator
from diffusers import DDPMScheduler, AutoencoderKL, UNet2DConditionModel, ControlNetModel
from transformers import CLIPTextModel, CLIPTokenizer
from torch.utils.data import DataLoader
from tqdm.auto import tqdm
import os

# --- ⚙️ 配置参数 (可调整) ---
# 显存优化设置：Batch Size 设为 2 或 4。如果爆显存，改成 1。
BATCH_SIZE = 4
# 梯度累积：如果是 1，意味着每一步都更新参数；如果是 4，意味着攒 4 步才更新一次（变相增大 Batch Size）
GRADIENT_ACCUMULATION_STEPS = 1
LEARNING_RATE = 1e-5
NUM_EPOCHS = 5 # 建议先跑 5 个 Epoch 看看效果，后续可以接着练
OUTPUT_DIR = "/content/drive/MyDrive/sat2street_model" # 模型保存到云盘
MODEL_ID = "runwayml/stable-diffusion-v1-5"

def train():
    # 1. 初始化 Accelerator (混合精度训练)
    accelerator = Accelerator(
        mixed_precision="fp16",
        gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS
    )

    # 2. 加载模型组件
    print("正在加载模型组件 (首次运行可能需要下载，请稍候)...")
    tokenizer = CLIPTokenizer.from_pretrained(MODEL_ID, subfolder="tokenizer")
    noise_scheduler = DDPMScheduler.from_pretrained(MODEL_ID, subfolder="scheduler")
    text_encoder = CLIPTextModel.from_pretrained(MODEL_ID, subfolder="text_encoder")
    vae = AutoencoderKL.from_pretrained(MODEL_ID, subfolder="vae")
    unet = UNet2DConditionModel.from_pretrained(MODEL_ID, subfolder="unet")

    # 🔥 关键：从 UNet 初始化一个新的 ControlNet
    # 它的输入通道会自动匹配（这里我们用卫星图 RGB 3通道，正好匹配）
    controlnet = ControlNetModel.from_unet(unet)

    # 3. 冻结参数 (只训练 ControlNet，其他不动)
    vae.requires_grad_(False)
    unet.requires_grad_(False)
    text_encoder.requires_grad_(False)
    controlnet.train()

    # 开启 Gradient Checkpointing (省显存神器)
    controlnet.enable_gradient_checkpointing()

    # 4. 准备数据加载器
    # 自定义 collate_fn：把文本 prompt 转成 token id
    def collate_fn(examples):
        pixel_values = torch.stack([example["pixel_values"] for example in examples])
        condition_pixel_values = torch.stack([example["condition_pixel_values"] for example in examples])
        prompts = [example["input_ids"] for example in examples] # 这里 dataset 返回的是字符串

        # Tokenize 文本
        inputs = tokenizer(
            prompts, max_length=77, padding="max_length", truncation=True, return_tensors="pt"
        )
        return {
            "pixel_values": pixel_values,
            "condition_pixel_values": condition_pixel_values,
            "input_ids": inputs.input_ids
        }

    # 使用你之前定义的 dataset
    train_dataloader = DataLoader(
        dataset, # 这里直接用你上一段代码生成的 dataset 变量
        shuffle=True,
        batch_size=BATCH_SIZE,
        collate_fn=collate_fn,
        num_workers=2
    )

    # 5. 准备优化器
    optimizer = torch.optim.AdamW(controlnet.parameters(), lr=LEARNING_RATE)

    # 把组件交给 Accelerator 管理
    controlnet, optimizer, train_dataloader = accelerator.prepare(
        controlnet, optimizer, train_dataloader
    )

    # 将不需要训练的模型移动到 GPU 并转为 fp16
    vae.to(accelerator.device, dtype=torch.float16)
    unet.to(accelerator.device, dtype=torch.float16)
    text_encoder.to(accelerator.device, dtype=torch.float16)

    # 6. 🚀 开始训练循环
    print(f"开始训练！总共有 {len(train_dataloader)} 个 Batch。")
    global_step = 0

    for epoch in range(NUM_EPOCHS):
        print(f"\nEpoch {epoch+1}/{NUM_EPOCHS} 正在进行...")
        progress_bar = tqdm(total=len(train_dataloader), disable=not accelerator.is_local_main_process)

        for step, batch in enumerate(train_dataloader):
            with accelerator.accumulate(controlnet):
                # --- A. 前向过程 ---
                # 1. 把街景图 (Target) 编码成 Latents
                latents = vae.encode(batch["pixel_values"].to(dtype=torch.float16)).latent_dist.sample()
                latents = latents * 0.18215

                # 2. 加噪
                noise = torch.randn_like(latents)
                timesteps = torch.randint(0, noise_scheduler.config.num_train_timesteps, (latents.shape[0],), device=latents.device).long()
                noisy_latents = noise_scheduler.add_noise(latents, noise, timesteps)

                # 3. 获取文本特征
                encoder_hidden_states = text_encoder(batch["input_ids"])[0]

                # 4. ControlNet 推理 (输入卫星图 condition)
                down_block_res_samples, mid_block_res_sample = controlnet(
                    noisy_latents,
                    timesteps,
                    encoder_hidden_states=encoder_hidden_states,
                    controlnet_cond=batch["condition_pixel_values"].to(dtype=torch.float16),
                    return_dict=False,
                )

                # 5. UNet 推理 (结合 ControlNet 的结果)
                noise_pred = unet(
                    noisy_latents,
                    timesteps,
                    encoder_hidden_states=encoder_hidden_states,
                    down_block_additional_residuals=[sample.to(dtype=torch.float16) for sample in down_block_res_samples],
                    mid_block_additional_residual=mid_block_res_sample.to(dtype=torch.float16),
                ).sample

                # --- B. 计算 Loss 并反向传播 ---
                loss = F.mse_loss(noise_pred.float(), noise.float(), reduction="mean")
                accelerator.backward(loss)
                optimizer.step()
                optimizer.zero_grad()

            progress_bar.update(1)
            progress_bar.set_postfix(loss=loss.item())
            global_step += 1

        # --- C. 保存模型 (每个 Epoch 结束存一次) ---
        save_path = os.path.join(OUTPUT_DIR, f"checkpoint-epoch-{epoch+1}")
        print(f"正在保存模型到: {save_path}")
        # Unwrap model 用于保存原始权重
        unwrapped_model = accelerator.unwrap_model(controlnet)
        unwrapped_model.save_pretrained(save_path)

    print("🎉 训练全部完成！")

# 运行主函数
train()

import torch
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, UniPCMultistepScheduler
from PIL import Image
import matplotlib.pyplot as plt
import os
import random

# ==========================================
# 1. 设置路径
# ==========================================
# 我们加载最后一个 Epoch 的模型，理论上效果最好
CHECKPOINT_PATH = "/content/drive/MyDrive/sat2street_model/checkpoint-epoch-5"
# 图片数据路径
IMAGE_DIR = "/content/sat2street_data/images"

def test_model():
    print(f"🚀 正在加载训练好的模型: {CHECKPOINT_PATH} ...")

    # 1. 加载组件
    # 注意：这里加载的是你训练的 ControlNet 部分
    controlnet = ControlNetModel.from_pretrained(CHECKPOINT_PATH, torch_dtype=torch.float16)

    # 加载底模 (SD v1.5) 并把你的 ControlNet 插进去
    pipe = StableDiffusionControlNetPipeline.from_pretrained(
        "runwayml/stable-diffusion-v1-5",
        controlnet=controlnet,
        torch_dtype=torch.float16,
        safety_checker=None
    ).to("cuda")

    # 使用 UniPC 采样器加速推理 (生成更快)
    pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)
    pipe.enable_model_cpu_offload() # 节省显存

    # 2. 随机找一张卫星图测试
    all_files = os.listdir(IMAGE_DIR)
    sat_files = [f for f in all_files if "sat" in f] # 筛选出卫星图

    if not sat_files:
        print("❌ 找不到测试图片！")
        return

    # 随机选一张
    test_file = random.choice(sat_files)
    sat_path = os.path.join(IMAGE_DIR, test_file)

    # 读取图片
    sat_image = Image.open(sat_path).convert("RGB").resize((512, 512))

    # 3. 开始生成
    print(f"🎨 正在生成对应街景 (输入: {test_file})...")

    # 提示词 (Prompt): 描述你想要的样子
    prompt = "street view photography, realistic, ground level view, high quality, 4k, urban area, clear sky"
    # 负面提示词 (Negative Prompt): 你不想要的样子
    n_prompt = "low quality, blurry, distorted, satellite view, aerial view, map, watermark"

    output_image = pipe(
        prompt,
        negative_prompt=n_prompt,
        image=sat_image,
        num_inference_steps=20,     # 步数
        controlnet_conditioning_scale=1.0, # 控制力度 (1.0 = 强力控制)
        guidance_scale=7.5
    ).images[0]

    # 4. 展示结果对比
    fig, ax = plt.subplots(1, 2, figsize=(12, 6))

    ax[0].imshow(sat_image)
    ax[0].set_title("Input: Satellite Image")
    ax[0].axis("off")

    ax[1].imshow(output_image)
    ax[1].set_title("Output: Generated Street View")
    ax[1].axis("off")

    plt.show()

# 运行测试
test_model()

!pip install torchmetrics lpips

import torch
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, UniPCMultistepScheduler
from PIL import Image
import matplotlib.pyplot as plt
import pandas as pd
import os
import random
import numpy as np

# ==========================================
# Configuration (配置区域)
# ==========================================
# Path to your trained model checkpoint (e.g., epoch 5)
# 模型路径
CHECKPOINT_PATH = "/content/drive/MyDrive/sat2street_model/checkpoint-epoch-5"

# Root directory of the dataset
# 数据集根目录
DATA_ROOT = "/content/sat2street_data"
CSV_PATH = os.path.join(DATA_ROOT, "pairs.csv")
IMAGE_DIR = os.path.join(DATA_ROOT, "images")

# Number of samples per category
# 每个类别测试的图片数量
SAMPLES_PER_CATEGORY = 10

# ==========================================
# Load Model (加载模型)
# ==========================================
print(f"🚀 Loading model from: {CHECKPOINT_PATH} ...")

# Load ControlNet
# 加载 ControlNet 组件
controlnet = ControlNetModel.from_pretrained(CHECKPOINT_PATH, torch_dtype=torch.float16)

# Load Stable Diffusion Pipeline with ControlNet
# 加载完整的生成管线
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet,
    torch_dtype=torch.float16,
    safety_checker=None
).to("cuda")

# Enable optimizations for speed and memory
# 开启加速和显存优化
pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)
pipe.enable_model_cpu_offload()

# ==========================================
# Main Evaluation Function (主评估函数)
# ==========================================
def evaluate_by_category():
    # Read the CSV file
    # 读取数据索引文件
    if not os.path.exists(CSV_PATH):
        print(f"❌ Error: CSV file not found at {CSV_PATH}")
        return

    df = pd.read_csv(CSV_PATH)

    # Get unique severity levels
    # 获取所有唯一的灾害等级标签
    severities = df['severity'].unique()
    print(f"📊 Found {len(severities)} severity categories: {severities}")

    # Iterate through each severity category
    # 遍历每一个灾害等级
    for severity in severities:
        print(f"\n{'='*20} Testing Category: {severity} {'='*20}")

        # Filter data for current severity and sample 10 items
        # 筛选当前类别的数据，并随机抽取 10 条
        category_df = df[df['severity'] == severity]

        # Handle case if less than 10 images exist
        # 如果样本不够 10 个，就取全部
        n_samples = min(SAMPLES_PER_CATEGORY, len(category_df))
        sampled_rows = category_df.sample(n_samples)

        # Create a large figure for this category
        # 为当前类别创建一个大画布
        fig, axes = plt.subplots(n_samples, 3, figsize=(20, 5 * n_samples))
        plt.subplots_adjust(wspace=0.1, hspace=0.2)

        # Loop through the sampled rows
        # 遍历抽取的每一行数据
        for idx, (_, row) in enumerate(sampled_rows.iterrows()):
            # Construct file paths
            # 构建文件路径 (使用 basename 防止路径前缀不匹配)
            sat_filename = os.path.basename(row["sat_path"])
            svi_filename = os.path.basename(row["svi_path"])

            sat_full_path = os.path.join(IMAGE_DIR, sat_filename)
            svi_full_path = os.path.join(IMAGE_DIR, svi_filename)

            # Load images
            # 读取图片
            try:
                sat_img = Image.open(sat_full_path).convert("RGB")
                gt_svi_img = Image.open(svi_full_path).convert("RGB")
            except FileNotFoundError:
                print(f"⚠️ Warning: Image not found for {sat_filename}")
                continue

            # Get Original Dimensions from Ground Truth
            # 获取真实街景的原始尺寸 (宽, 高)
            original_width, original_height = gt_svi_img.size

            # Preprocess Satellite Image (Resize to 512x512 for Model)
            # 卫星图缩放到 512x512 以喂给模型
            input_sat = sat_img.resize((512, 512), Image.BICUBIC)

            # Generate Prompt
            # 生成提示词
            prompt = f"street view photography, realistic, ground level view, {severity.replace('_', ' ').lower()}, high quality, 4k, urban area"
            negative_prompt = "low quality, blurry, satellite view, aerial view, map, watermark, text"

            # Run Inference
            # 执行推理生成
            with torch.inference_mode():
                generated_output = pipe(
                    prompt,
                    negative_prompt=negative_prompt,
                    image=input_sat,
                    num_inference_steps=20,
                    controlnet_conditioning_scale=1.0,
                    guidance_scale=7.5
                ).images[0]

            # Post-process: Resize Generated Image to Match Original Ground Truth Size
            # 后处理：强制将生成的图片缩放回原始尺寸
            final_output = generated_output.resize((original_width, original_height), Image.LANCZOS)

            # Plotting (Display in columns)
            # 绘图：左(卫星) - 中(生成) - 右(真实)

            # Column 1: Input Satellite
            # 第一列：输入卫星图
            ax = axes[idx] if n_samples > 1 else axes # Handle single row case
            ax[0].imshow(sat_img) # Show original sat
            ax[0].set_title(f"Input Satellite\n({sat_filename})", fontsize=10)
            ax[0].axis("off")

            # Column 2: Generated Street View (Restored Size)
            # 第二列：生成的街景 (已还原尺寸)
            ax[1].imshow(final_output)
            ax[1].set_title(f"Generated (Resized to {original_width}x{original_height})", fontsize=10, color="blue")
            ax[1].axis("off")

            # Column 3: Ground Truth (Original Size)
            # 第三列：真实街景 (原始尺寸)
            ax[2].imshow(gt_svi_img)
            ax[2].set_title(f"Ground Truth\n({severity})", fontsize=10)
            ax[2].axis("off")

        # Show the plot for this category
        # 显示当前类别的图像组
        print(f"✅ Visualization for {severity} ready:")
        plt.show()

# Run the evaluation
# 运行主程序
if __name__ == "__main__":
    evaluate_by_category()

import os
import torch
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, UniPCMultistepScheduler
from PIL import Image
import pandas as pd
from tqdm.auto import tqdm

# ================= 配置区域 =================
# 模型路径
CHECKPOINT_PATH = "/content/drive/MyDrive/sat2street_model/checkpoint-epoch-5"
# 数据路径
DATA_ROOT = "/content/sat2street_data"
CSV_PATH = os.path.join(DATA_ROOT, "pairs.csv")
IMAGE_DIR = os.path.join(DATA_ROOT, "images")

# 保存结果的根目录
RESULTS_DIR = "/content/evaluation_results"
GEN_DIR = os.path.join(RESULTS_DIR, "generated")      # 存放 AI 生成的图
GT_DIR = os.path.join(RESULTS_DIR, "ground_truth")    # 存放 真实参考图

# 测试数量 (设为 None 则测试全部数据，建议先测 50-100 张试试)
NUM_TEST_SAMPLES = 100
# ===========================================

def generate_and_save():
    # 1. 创建文件夹
    os.makedirs(GEN_DIR, exist_ok=True)
    os.makedirs(GT_DIR, exist_ok=True)

    # 2. 加载模型
    print("🚀 Loading model...")
    controlnet = ControlNetModel.from_pretrained(CHECKPOINT_PATH, torch_dtype=torch.float16)
    pipe = StableDiffusionControlNetPipeline.from_pretrained(
        "runwayml/stable-diffusion-v1-5", controlnet=controlnet, torch_dtype=torch.float16, safety_checker=None
    ).to("cuda")
    pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)
    pipe.enable_model_cpu_offload()

    # 3. 读取数据
    df = pd.read_csv(CSV_PATH)
    if NUM_TEST_SAMPLES:
        df = df.sample(min(NUM_TEST_SAMPLES, len(df)), random_state=42) # 随机抽样

    print(f"📊 Starting generation for {len(df)} images...")

    for idx, row in tqdm(df.iterrows(), total=len(df)):
        try:
            # 路径处理
            sat_name = os.path.basename(row["sat_path"])
            svi_name = os.path.basename(row["svi_path"])

            sat_path = os.path.join(IMAGE_DIR, sat_name)
            svi_path = os.path.join(IMAGE_DIR, svi_name)

            # 读取图片
            sat_img = Image.open(sat_path).convert("RGB")
            gt_img = Image.open(svi_path).convert("RGB")

            # 记录原始尺寸用于还原
            orig_w, orig_h = gt_img.size

            # 生成
            input_sat = sat_img.resize((512, 512), Image.BICUBIC)
            prompt = f"street view photography, realistic, ground level view, {row['severity'].replace('_', ' ').lower()}, high quality, 4k"

            with torch.inference_mode():
                gen_img = pipe(
                    prompt,
                    image=input_sat,
                    num_inference_steps=20,
                    controlnet_conditioning_scale=1.0
                ).images[0]

            # 还原尺寸
            gen_img = gen_img.resize((orig_w, orig_h), Image.LANCZOS)

            # 保存 (使用相同的索引名，方便对应)
            save_name = f"{idx:05d}.png"
            gen_img.save(os.path.join(GEN_DIR, save_name))
            gt_img.save(os.path.join(GT_DIR, save_name))

        except Exception as e:
            print(f"⚠️ Error processing {sat_name}: {e}")

    print(f"✅ All images saved to {RESULTS_DIR}")

if __name__ == "__main__":
    generate_and_save()

import os
import torch
import pandas as pd
import numpy as np
from PIL import Image
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, UniPCMultistepScheduler

# Metrics libraries
from torchmetrics.image import StructuralSimilarityIndexMeasure, PeakSignalNoiseRatio, LearnedPerceptualImagePatchSimilarity
from torchmetrics.image.fid import FrechetInceptionDistance
from torchvision.io import read_image

# ==========================================
# 1. Configuration (配置区域)
# ==========================================
# Paths (路径设置)
CHECKPOINT_PATH = "/content/drive/MyDrive/sat2street_model/checkpoint-epoch-5" # 你的模型路径
DATA_ROOT = "/content/sat2street_data"
CSV_PATH = os.path.join(DATA_ROOT, "pairs.csv")
IMAGE_DIR = os.path.join(DATA_ROOT, "images")

# Output directory for evaluation results
# 结果保存根目录
EVAL_ROOT = "/content/evaluation_results_by_category"

# Number of samples to test per category (Set to None for all images)
# 每个类别测试多少张？建议设为 50 或 100 以获得准确的 FID。如果设为 None 则测试全部。
SAMPLES_PER_CATEGORY = 20

# ==========================================
# 2. Model Loading (加载模型)
# ==========================================
print(f"🚀 Loading Model from {CHECKPOINT_PATH}...")
controlnet = ControlNetModel.from_pretrained(CHECKPOINT_PATH, torch_dtype=torch.float16)
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet,
    torch_dtype=torch.float16,
    safety_checker=None
).to("cuda")
pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)
pipe.enable_model_cpu_offload()

# ==========================================
# 3. Generation & Saving Function (生成并保存)
# ==========================================
def generate_and_save_images():
    print("\n" + "="*50)
    print("🎨 Step 1: Generating and Saving Images by Category...")
    print("="*50)

    df = pd.read_csv(CSV_PATH)
    severities = df['severity'].unique() # 获取所有分类，例如 ['0_Minor', '1_Moderate', '2_Severe']

    for severity in severities:
        print(f"\n📂 Processing Category: {severity}")

        # 1. Create directories for this category
        # 为当前类别创建文件夹: generated 和 ground_truth
        cat_gen_dir = os.path.join(EVAL_ROOT, severity, "generated")
        cat_gt_dir = os.path.join(EVAL_ROOT, severity, "ground_truth")
        os.makedirs(cat_gen_dir, exist_ok=True)
        os.makedirs(cat_gt_dir, exist_ok=True)

        # 2. Filter and sample data
        # 筛选并抽样数据
        cat_df = df[df['severity'] == severity]
        if SAMPLES_PER_CATEGORY:
            cat_df = cat_df.sample(min(SAMPLES_PER_CATEGORY, len(cat_df)), random_state=42)

        # 3. Loop through images
        # 遍历图片进行生成
        for idx, row in tqdm(cat_df.iterrows(), total=len(cat_df), desc=f"{severity}"):
            try:
                # Load images
                # 读取图片
                sat_path = os.path.join(IMAGE_DIR, os.path.basename(row["sat_path"]))
                svi_path = os.path.join(IMAGE_DIR, os.path.basename(row["svi_path"]))

                sat_img = Image.open(sat_path).convert("RGB")
                gt_img = Image.open(svi_path).convert("RGB") # Ground Truth

                # Get Original Size for restoration
                # 获取真实图片的原始尺寸 (例如 1024x512)
                orig_w, orig_h = gt_img.size

                # Resize input for model (512x512)
                # 缩放输入以适配模型
                input_sat = sat_img.resize((512, 512), Image.BICUBIC)

                # Generate
                # 生成
                prompt = f"street view photography, realistic, ground level view, {severity.replace('_', ' ').lower()}, high quality, 4k"
                with torch.inference_mode():
                    gen_img = pipe(
                        prompt,
                        image=input_sat,
                        num_inference_steps=20,
                        controlnet_conditioning_scale=1.0
                    ).images[0]

                # Resize Generated Image back to Original Size
                # 🔥 关键步骤：将生成的图 resize 回原始尺寸 (1024x512)
                gen_img = gen_img.resize((orig_w, orig_h), Image.LANCZOS)

                # Save Images (Use same filename for easy matching)
                # 保存图片
                save_name = f"{idx}.png"
                gen_img.save(os.path.join(cat_gen_dir, save_name))
                gt_img.save(os.path.join(cat_gt_dir, save_name))

            except Exception as e:
                print(f"⚠️ Error: {e}")

# ==========================================
# 4. Metrics Calculation Function (计算指标)
# ==========================================
def calculate_metrics_by_category():
    print("\n" + "="*50)
    print("📊 Step 2: Calculating Metrics (SSIM, PSNR, LPIPS, FID)...")
    print("="*50)

    device = "cuda" if torch.cuda.is_available() else "cpu"

    # Initialize Metrics
    # 初始化指标计算器
    ssim = StructuralSimilarityIndexMeasure(data_range=1.0).to(device)
    psnr = PeakSignalNoiseRatio(data_range=1.0).to(device)
    lpips = LearnedPerceptualImagePatchSimilarity(net_type='vgg').to(device)
    # Note: FID usually requires 64 or 2048 features.
    # For small batch size, we use a smaller feature dimension to avoid errors if needed, but 2048 is standard.
    fid = FrechetInceptionDistance(feature=2048).to(device)

    # Prepare DataFrame to store results
    # 准备表格存储结果
    results_list = []

    # Get all categories from the folder structure
    # 从文件夹结构中获取所有类别
    categories = [d for d in os.listdir(EVAL_ROOT) if os.path.isdir(os.path.join(EVAL_ROOT, d))]

    for category in categories:
        print(f"\n📉 Calculating metrics for: {category} ...")

        gen_dir = os.path.join(EVAL_ROOT, category, "generated")
        gt_dir = os.path.join(EVAL_ROOT, category, "ground_truth")

        # Get list of files
        files = os.listdir(gen_dir)

        # Temporary lists for per-image metrics
        cat_ssim, cat_psnr, cat_lpips = [], [], []

        # Reset FID for each category
        fid.reset()

        for f in tqdm(files, desc="Processing pairs"):
            gen_path = os.path.join(gen_dir, f)
            gt_path = os.path.join(gt_dir, f)

            # Read images into Tensor [0, 1]
            # 读取图片并转为 Tensor
            gen_tensor = read_image(gen_path).float() / 255.0
            gt_tensor = read_image(gt_path).float() / 255.0

            # Add batch dimension (1, C, H, W)
            gen_tensor = gen_tensor.unsqueeze(0).to(device)
            gt_tensor = gt_tensor.unsqueeze(0).to(device)

            # Calculate Paired Metrics
            # 计算成对指标
            cat_ssim.append(ssim(gen_tensor, gt_tensor).item())
            cat_psnr.append(psnr(gen_tensor, gt_tensor).item())
            # LPIPS expects input in range [-1, 1]
            cat_lpips.append(lpips(gen_tensor * 2.0 - 1.0, gt_tensor * 2.0 - 1.0).item())

            # Update FID stats (requires uint8 [0, 255] format)
            # 更新 FID 统计数据 (需要 uint8 格式)
            gen_uint8 = read_image(gen_path).unsqueeze(0).to(device)
            gt_uint8 = read_image(gt_path).unsqueeze(0).to(device)
            fid.update(gt_uint8, real=True)
            fid.update(gen_uint8, real=False)

        # Compute FID for the whole category
        # 计算该类别的 FID
        try:
            fid_score = fid.compute().item()
        except Exception as e:
            print(f"⚠️ Warning: FID calculation failed (maybe too few samples). Error: {e}")
            fid_score = float('nan')

        # Store results
        # 存储该类别的平均结果
        results_list.append({
            "Method": "Sat2Street (Ours)",
            "Category": category,
            "SSIM ↑": sum(cat_ssim) / len(cat_ssim),
            "PSNR ↑": sum(cat_psnr) / len(cat_psnr),
            "FID ↓": fid_score,
            "LPIPS ↓": sum(cat_lpips) / len(cat_lpips)
        })

    # Create Final DataFrame
    # 创建最终表格
    df_results = pd.DataFrame(results_list)

    # Calculate Average across all categories
    # 计算所有类别的平均值
    avg_row = df_results.iloc[:, 2:].mean().to_dict()
    avg_row["Method"] = "Sat2Street (Ours)"
    avg_row["Category"] = "AVERAGE"

    # Use pd.concat instead of append
    df_results = pd.concat([df_results, pd.DataFrame([avg_row])], ignore_index=True)

    # Display Table
    # 显示表格
    print("\n" + "="*60)
    print("🏆 FINAL EVALUATION RESULTS (按类别分类指标)")
    print("="*60)
    print(df_results.to_string(index=False))

    # Save to CSV
    # 保存结果文件
    save_path = os.path.join(EVAL_ROOT, "final_metrics.csv")
    df_results.to_csv(save_path, index=False)
    print(f"\n✅ Results saved to: {save_path}")

# ==========================================
# 5. Run Execution (运行主程序)
# ==========================================
if __name__ == "__main__":
    # Step 1: Generate Images
    generate_and_save_images()

    # Step 2: Calculate Metrics
    calculate_metrics_by_category()